### ISSUE TITLE
Что с рефссылкой? 

### ISSUE THREAD

**Issue by Seler1972** [KriptoSlava/eGOLD#13]
Проблема захвата 100 монетных ордеров решается созданием минимального ордера не 100, а 110 монет. В любом случае покупатель должен выйти на продавца по его реквизитам, а продавец заинтересован продать ордер и всегда переведет аванс в 15 монет новому участнику монеты. 
После перевода аванса покупатель сможет захватить 110 ордер. 
В случае мошенничества в размере 15 монет мошенник засветит свои контакты и в следующий раз ему для воровства 15 монет надо создавать новый аккаунт. 

Без реферальной ссылки проект теряет 95% своих преимуществ. 
Просьба вернуть реф ссылку в следующую версию кошелька и ноды. 
Все владельцы монет - акционеры проекта и самовольно лишать монету главного преимущества крайне недальновидно.

**Comment by KriptoSlava** [comment]
С версии 1.61, ноды не создают кошельки, так как от этого было больше вреда, чем пользы: мошенники могли списать все средства с кошелька регистрации, так же они могли безнаказанно автоматически захватывать лоты по 100 монет. И основной момент - это потеря новых пользователей... Почему так происходило? При заходе нового пользователя без помощи другого человека, он сам себе создавал кошелёк, заходил в него и также быстро выходил, так как ничего не понимал в нём... Потом вернуть этого пользователя, который первоначально заинтересовался монетой было невозможно. У него просто отбивалось всё желание. Всем новым пользователям всегда нужно объяснять что и к чему. Замена создания нового кошелька нодой - это размещение объявления с предложением создания кошелька на странице входа с контактами для связи.

**Comment by Seler1972** [comment]
В настоящее время в версии 1.63 проблема не решена, мошенники так же захватывают ордера в 100 монет. Почему разработчик отказался от реферальной ссылки и продвижения проекта с помощью этого уникального для криптовалют инструмента? 
Решений много:
1. Поднять сумму минимального ордера до 110 монет, 
2. Вместо 3х монет, давать 2 монеты при активации кошелька по рефссылке.
3. И много других. 

Просьба ответить на поставленные вопросы развёрнуто. 
Акционеры монеты обеспокоены количеством регистраций за сутки после последних обновлений - это 1-2 кошелька за сутки
