### ISSUE TITLE
запрос функции: Добавить в кошелёк отображение текущего курса монеты eGOLD

### ISSUE THREAD

**Issue by sereg1k** [KriptoSlava/eGOLD#3]
В данный момент времени в кошельке очень не хватает возможности просмотра текущего курса монеты eGOLD по отношению к другим валютам. Сейчас для того, чтобы узнать стоимость монеты приходится открывать сайт, на котором указан текущий курс, т.е. совершаются лишние действия, а это отнимает время и очень неудобно. Хотелось бы, чтобы при входе в кошелёк сразу был виден курс монеты. 

**Дополнение 1:** так как у нас монета равна 1/100000 тройской унции золота (XAU), то при первом входе в кошелёк думаю логично было бы сделать первоначальное отображение курса в таком виде - 1 eGOLD = 0.00001 XAU. Если пользователь хочет, чтобы курс отображался по отношению к рублю (доллару, евро,...), то в выпадающем списке должен будет выбрать нужную ему валюту (1 eGOLD = xx.xx RUB или 1 eGOLD = xx.xx USD или 1 eGOLD = xx.xx EUR, ...).

**Дополнение 2:** вне зависимости от того, к какой ноде происходит подключение, текущий курс должен быть одинаковым на всех кошельках.

**Дополнение 3:** после выхода из кошелька выбор валюты должен сохраняться.

**Comment by KriptoSlava** [comment]
❗️ Многие пишут по курсу и просят его добавить в eGOLD.html кошелёк. 

Если это сделать, кошелёк начнёт подтягивать курсы со сторонних сервисов и станет зависим от них. В них периодически меняется api, иногда они не доступны и так далее. Курс сейчас отправляется сторонним сервисом в объявления. Также курс есть в телеграмм кошельке. И этого достаточно для решения задачи с курсом. Другого решения не будет. 

* Если нужно посчитать курс для криптовалют, сначала пересчитываем по текущему курсу в доллары, а потом доллары пересчитываем в нужную криптовалюту.
