### ISSUE TITLE
запрос функции: Добавить в кошелёк калькулятор eGOLD <-> RUB (USD, EUR, BTC) 

### ISSUE THREAD

**Issue by sereg1k** [KriptoSlava/eGOLD#4]
Например, я открываю кошелёк и хочу отправить монеты eGOLD на сумму в 54321 рубля. Сколько это будет монет? Трудно сказать. Сейчас для того, чтобы узнать количество монет для отправления нужно открывать сайт, на котором указан текущий курс, затем открывать калькулятор и производить расчёты по формуле: 54321/курс=монеты, а это отнимает время и очень неудобно. Хотелось бы, чтобы в кошельке при вводе суммы в рублях (eGOLD) расчёты производились автоматически. Но это можно будет сделать только при добавлении в кошелёк [функции отображения текущего курса монеты eGOLD]( https://github.com/KriptoSlava/eGOLD/issues/3).

**Comment by KriptoSlava** [comment]
**❗️ Многие пишут по курсу и просят его добавить в eGOLD.html кошелёк.** 

Если это сделать, кошелёк начнёт подтягивать курсы со сторонних сервисов и станет зависим от них. В них периодически меняется api, иногда они не доступны и так далее. Курс сейчас отправляется сторонним сервисом в объявления. Также курс есть в телеграмм кошельке. И этого достаточно для решения задачи с курсом. Другого решения не будет. 

_* Если нужно посчитать курс для криптовалют, сначала пересчитываем по текущему курсу в доллары, а потом доллары пересчитываем в нужную криптовалюту._
