### ISSUE TITLE
Запрос на добавление в код eGOLD.html ссылок на основные ресурсы и документацию

### ISSUE THREAD

**Issue by givikoenig** [KriptoSlava/eGOLD#6]
САБЖ
Предлагаю что-то вроде этого:

`
<div class="container">
    <div class="page_not_login show-page">
      <div class="page_ext_link">
          <a href="https://github.com/KriptoSlava/eGOLD" target="blank">Архив версий GitHub</a>
          <br>
          <a href="https://telegra.ph/Spisok-izmenenij-v-versiyah-eGOLD-01-08" target="blank">Список изменений версий eGOLD</a>
          <br>
          <a href="https://github.com/KriptoSlava/eGOLD/raw/master/eGOLD_WhitePaperRU.pdf">Белая книга (eGOLD_WhitePaperRU.pdf)</a>
      </div>
    </div>
  </div>
`

и css:

`.page_ext_link {
  width: 100%;
  text-align: center;
  
}
.page_ext_link a {
  font-size: 20px;
  color: #E6A219;
  text-decoration: none;
}`
![eGOLD_ext_links](https://user-images.githubusercontent.com/25180507/142770402-fdc673b1-f8d5-4657-89c6-49987adda7a8.jpg)

**Comment by KriptoSlava** [comment]
БлагоДарю за идею. Обдумывается. Но сторонние ресурсы и ссылки на них не могут быть в кошельке. Он автономный.
