### ISSUE TITLE
парольная фраза больше не работает

### ISSUE THREAD

**Issue by IgorVK7** [KriptoSlava/eGOLD#7]
Здравствуйте. У меня после того как я создал новый кошелек для знакомого и подтвердил парольной фразой, парольная фраза больше не работает. При вводе мигает сиреневая рамка. Версия кошелька 1.53, МД5 проверял. В чем может быть проблема не подскажете ?

**Comment by KriptoSlava** [comment]
Перейдите в чат общий и там напишите вопрос: https://t.me/eGOLDpro

Скорее всего Вы не до конца скопировали закрытый ключ или не тот закрытый ключ используете. Также могло не пройти время смены ключа, а это около 2-х минут после смены закрытого ключа.

**Comment by KriptoSlava** [comment]
В любом случае, рекомендую всегда проверять парольную фразу после её смены.

**Comment by IgorVK7** [comment]
Добрый вечер. Я не менял себе парольную фразу. Я создал кошелек для реферала и подтвердил своей парольной фразой. Кошельком пользуюсь давно. На нем 25 рефералов. Пробую с разными нодами. Пока не получается. Пытаюсь отправить 1 монету рефералу...парольная фраза не берется. Кошелек G-8949-21970-6104-93866  Парольную фразу вижу полностью при уменьшении в ворде. Копирую полностью.  Что можно еще сделать подскажете?

**Comment by KriptoSlava** [comment]
Просто так такого не бывает. Может быть Вы заменили Ваш закрытый ключ случайно ключом от нового кошелька и сохранили? В любом случае надо разбираться. Здесь такие вопросы не нужно задавать. Пишите в общем чате о котором написал выше.

**Comment by Helpochka** [comment]
Игорь! Имею практический опыт подобных вашему случаев.  Попробуйте сменить  Ноду в кошельке и, возможно ваша фраза сработает. 
А еще очень рекомендую копировать фразу для сохранения в текстовый документ дважды. И вторую сохраненную копию никогда не трогать и приписать рядом:ЭТАЛОН. Так как при копировании  может что то исказиться ...если дрожащей рукой и с разной скоростью и остановками копировать.

**Comment by KriptoSlava** [comment]
**Закрытый ключ, который мне был предоставлен в ходе общения, имеет публичный ключ:**
0741152603f2246819d22fc013482a0c203f2acd2618229512c212720ddd1fc5033a2f74275b15751f84246e17f8004a2c6c2ea3067e2a06008d052f0a2e0a4b22e8088617e126d92671052c122f184b00dd296b26da0b8b23ef194129fc154619eb2e9a173412c82746280207220d620f2423081b0726f321ab2340269d1ccd088002e50bf923962ad20a3a1d5a0a1c20fd272503df25931b330eca293c2ded04ac0d8b2c5403ad27710b7b217908691e1b200c0cde20860c20248116d7205e27211602295b231011981fff2769248f259d287911da0c101f3a0c3b27f30a4109c2174b100117631a2408e220a22bf1091e2951177e2bc91d462e251f0603cc10

**А в последней транзакции использовался закрытый ключ, который имеет публичный ключ:** 
07f52dee0ac2260509890cb4034c17a228ee0ff30eef14721acf2e162a0a197712d618642c482f251d950fb30f09246f11832307036615df01ef0cfc0e070b611a392867142d03aa1de108c51549287d1a340652048219d51e232da81c311bbd052d0f5707132b65054f0b7f08df1a982df71cb123e31e0f2e4211192c6818c728101ed020492c852ef50a1d2c4c0ee912e32b512a722ef921a81e5f2be822c415e60f63058101dc04a701591b7111ae1c7f0acc2843295b0aa810c2236f092015a20c7520c9113629271f4c00b826122922144c087a093201fb0a3223a82e142cf225ae2356180222ee0a29006b20a0066e17bd2ff2286c17500e15221224aa09

**Можно сделать вывод, что для совершения транзакции используется не тот закрытый ключ.**

**Comment by KriptoSlava** [comment]
Нужно различать публичный и закрытый ключ. Закрытый ключ хранится в секрете у каждого пользователя. И именно с помощью него совершаются транзакции в любой криптовалюте. Публичный ключ получается из закрытого ключа с помощью преобразования. Из публичного ключа восстановить закрытый ключ нереально, но публичный ключ требуется для проверки транзакции и сопоставления транзакции подписанной закрытым ключом и однозначно определяет владельца кошелька. В eGOLD публичный ключ по последней транзакции хранится до 7 дней в истории транзакций и потом удаляется навсегда. А его хэш остаётся и повышает безопасность всей системы. По хэшу публичного ключа вычисляется принадлежность подписи транзакции конкретному кошельку.

**Comment by KriptoSlava** [comment]
Так как в любой криптовалюте закрытый ключ хранится только у пользователя, восстановить его невозможно. Он не хранится на нодах и вообще нигде, кроме как у пользователя. Более подробно об закрытом и открытом ключе и, в частности, в криптовалютах можно прочитать в интернете.

В дальнейшем, такие вопросы не будут разбираться, так как пользователи периодически теряют свои закрытые ключи и разбирать каждый случай, просто чисто физически невозможно. Нужно запомнить, что утеря ключа равна утери всего кошелька вместе с его балансом и всеми рефералами.

**Comment by KriptoSlava** [comment]
В продолжении добавлю, что был найден реферал кошелька G-8949-21970-6104-93866 с ранее использованным таким же открытым ключом от мне предоставленного закрытого ключа. То есть, был перепутан закрытый ключ. Этот реферальный кошелёк уже изменил закрытый ключ на другой и естественно у него сменился и открытый.
