### ISSUE TITLE
Возможность продлять ордера p2p на любой срок (месяц и более)

### ISSUE THREAD

**Issue by short-stroke** [KriptoSlava/eGOLD#8]
В телеграм чате рассказали, как "кинули", минимум 2-х человек на 3 000 монет, за покупку чая по почте, т.к. не возможно было провести сделку через р2р, из за короткого срока действия ордеров.

Если бы была возможность устанавливать произвольный (фиксированный, по договорённости обеих сторон) срок действия ордера, у мошенников не было бы лазейки, и появилась возможность продавать/покупать товары за монету, назначив фиксированную дату окончания сделки.

Спасибо, за монету!

**Comment by KriptoSlava** [comment]
Идея очень хорошая. Возможно в будущем будет такая возможность. Но текущая реализация не позволяет это сделать, всё завязано на строгом времени и при изменении одного времени, последствия наступают для другого.
