### ISSUE TITLE
Ссылки в поле контактов P2P

### ISSUE THREAD

**Issue by givikoenig** [KriptoSlava/eGOLD#9]
Возможно ли сделать так, чтобы, если в поле "Контакт" раздела p2p указана ссылка, то по клику на ней открывался  бы и соответствующий ресурс, а не только  фильтр поиска по контакту?
Например:
 https://api.whatsapp.com/send?phone=7XXXXXXXXXX
или
https://t.me/SomeTelegramNicName

**Comment by KriptoSlava** [comment]
БлагоДарю за сообщению. В P2P сделках намерено отсутствует преобразование ссылок к кликабельности, чтобы не было случайных переходов по ним. Это сделано с целью защиты от фишинга и других злонамеренных действий.
